# Generated by Django 5.2.5 on 2025-08-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = []
