# Generated by Django 4.2.10 on 2025-06-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_chatbotconversation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatbotconversation",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="chatbotconversation",
            name="chatbot_type",
            field=models.CharField(
                choices=[("indeed", "Indeed Bot"), ("gmtt", "GMTT Bot")], max_length=10
            ),
        ),
    ]
