# Generated by Django 5.2.3 on 2025-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_chatbotconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconversation',
            name='session_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
