# Generated by Django 4.2.10 on 2025-06-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_alter_chatbotconversation_options_and_more"),
        ("authapp", "0003_register_alter_contactus_options"),
    ]

    operations = []
