# Generated by Django 5.2.4 on 2025-07-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_chatbotconversation_session_id'),
        ('authapp', '0004_merge_20250623_1528'),
    ]

    operations = [
    ]
