# Generated by Django 5.1.7 on 2025-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_merge_20250723_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotconversation',
            name='chatbot_type',
            field=models.CharField(choices=[('indeed', 'Indeed'), ('gmtt', 'GMTT')], max_length=10),
        ),
    ]
