# Generated by Django 5.2.4 on 2025-08-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_chatbotconversation_chatbot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('is_priority', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['base_url'], name='authapp_scr_base_ur_b2f588_idx'), models.Index(fields=['is_priority'], name='authapp_scr_is_prio_55c13f_idx')],
            },
        ),
    ]
