hinglish_keywords = [
    "aap", "aaap", "ap", "tum", "tu", "main", "mai", "mein", "me", "hum", "ham",
    "upar", "neeche", "neecha", "niche", "piche", "aage", "pichey", "peechay",
    "kamar", "sambhal", "girna", "gir", "gira", "gayi", "gaya", "gire", "fisal", "fisalna",
    "bachav", "bachao", "bachaye", "bachana", "suraksha", "surakshit", "surakshitth",
    "pahen", "pehna", "pahna", "pahenna", "lagao", "baandh", "baandhna", "baandho",
    "kharab", "toota", "tooti", "tootna", "dhyaan", "dhyan", "dhyanse", "dekho", "dekhna",
    "sun", "sunna", "sunke", "suno", "bol", "bolo", "batana", "bataye", "sambhalke",
    "sambhalkar", "pakad", "pakdo", "sahi", "galat", "uparwala", "nichla", "kaam", "kaamkar",
    "kaamwala", "kaamwali", "mehnat", "samaan", "saman", "uthao", "uthaana", "uthaake",
    "pahanlo", "pahanna", "helmat", "hath", "haath", "pair", "paer", "latka", "latak",
    "latakna", "pakaad", "zor", "zorlagao", "seedi", "seedhi", "seediyan", "sidhi", "charna",
    "utarna", "sambhalna", "nicheutro", "uparjao", "seediutro", "pakadkar", "sambhalkar",
    "bachaav", "kapat", "kinara", "kinare", "lagaav", "lagao", "baandhna", "huk",
    "jodne", "jor", "jorna", "surakshabelt", "rop", "ropese", "straplagaao", "jodkar", "pakadne", "lagaakar", "bhari", "halka", "patla", "majboot",
    "kacha", "kachcha", "tootega", "girjaoge", "latakte", "balkoni", "kone", "koni", "konia",
    "lehar", "hawa", "tez", "tezhawa", "zamin", "chhat", "chat", "uparchadho", "uparse",
    "patra", "kacha", "dhacha", "dhacha", "safari", "safai", "kachra", "nichese", "neechesey",
    "uparwalo", "pakdalo", "seediwala", "ghoom", "phisal", "samne", "diwal", "diwaar", "patang",
    "bijli", "tar", "taron", "bijlipole", "bijlikam", "electrishock", "jhatka", "hatheli",
    "kandha", "gardan", "peti", "jodkar", "jodna", "samasya", "raksha",
    "rukawat", "girne", "dikhayi", "awaaz", "cheekhna", "bachne", "bachaya", "mudke", "kaamchor",
    "uparkakaam", "paani", "geela", "phisalna", "bachake", "haathpakadna", "balkise",
    "sambhalkeutro", "isara", "ishara", "isare", "haathutthana", "rukjao",
    "rukna", "rukne", "rukgaye", "sambhaloge", "girte", "mehnatkaro", "sath", "ekjut",
    "jodmilke", "uparwala", "kaamnahi", "kaamsahi", "kaamgalat", "ropelagaao", "chadhai",
    "utrai", "latkegaya", "girrahahai", "girrahahun", "khinchav", "khinchna", "kheenchkar",
    "zorlagakar", "zorpakadna", "asurakshit", "surakshitnahin", "girnewala", "girnewali",
    "dangerzone", "khatra", "khatrewala", "khatrawali", "khatreka", "surakshazone",
    "surakshajaga", "helmetpahno", "baandhlo", "baandhna", "hooklagao", "ropetie",
    "safedhaaga", "peelirope", "kalarop", "lambirope", "kamjorrope", "strongrope",
    "tightrope", "surakshawaali", "jorlagaao", "saamaanuthao", "petipahno", "kamarbandh",
    "kamarbelt", "kandhabelt", "safetykapat", "saambhalke", "saambhalkar", "seedhilagao",
    "nichematjao", "uparchadhna", "konepar", "konepe", "balkipar", "platformpar",
    "scaffoldwala", "scaffoldingkaam", "kaamparsuraksha",
    "petibandho", "harnessbandho", "lifeline", "lifelagaao", "lifesupport", "lifebelting",
    "toollagaao", "toolgirna", "hathtool", "hatthathiyar", "uthanekaam",
    "laddersechadhna", "ladderutro", "ladderutarna", "ladderbhi", "ladderthik",
    "ladderfix", "laddersupport", "ghisakheech", "kheechna", "kheenchkar", "hookfix",
    "tikatight", "patitight", "beltlagao", "beltpahno", "chadhkar", "nichese", "upparjakar",
    "kaamnipura", "kaambandh", "kaamsecure", "majaknahi", "gambhir", "zindagikaam", "surakshamitra",
    "jodlagao", "jojsafety", "pakadlena", "girnekebaad", "girneka", "bachnekaliae",
    "pehlechup", "sunochup", "khabardar", "saavdhan", "sambhaljayo", "sambhallo", "dekhke",
    "dekhkar", "thambajao", "dekhkaruthao", "zordetena", "zorlagadena", "hathlagakar",
    "latakrahahai", "latakrahahun", "nichchese", "uparse", "uparwalko", "chadhnewala",
    "chadhnewali", "utarnayogya", "chalnekaam", "girnewala", "girnekaam", "hathlagao",
    "beltsupport", "surakshabelt", "maikaro", "safetybolna", "dangercheekhna", "bachnacheekhna",
    "ruknaawaaz", "rukjaye", "ropepakad", "hookpakad", "baandhkar", "toolgirrahahai",
    "upargirrahahai", "ropekheenchna", "suraksharassi", "rassibaandhna", "rassipakdo",
    "saamanneeche", "girnasamaan", "girnewalatool", "pehnolifeline", "pehnorassi",
    "chhotirope", "badrassi", "phattirope", "surakhitkaam", "jeevanraksha", "rakshahelmet",
    "rakshabelt", "rassichaahiye", "hooktight", "hooklaga", "hookdalo", "hookbaandho",
    "ropebaandho", "patibandho", "shoulderbelt", "girawale", "sambhalwakt",
    "surakshadekho", "kaamdekho", "upardekhkar", "neechedhyan", "rassiuthao", "patiuthao",
    "petisebandho", "kandhase", "kamarse", "helmettheek", "safetykaam", "guardrailskaam","acha", "thik hai", "chalta hai", "kya baat hai", "mast", "timepass", 
    "jugaad", "bhidu", "yaar", "pagal", "nashta", "khana", "pina", 
    "ghar", "kaam", "dhanda", "bazaar", "sasta", "mehenga", "kitna", 
    "kahan", "kaun", "kyun", "kab", "achcha", "thoda", "zyada", "kam", 
    "badhiya", "bekar", "dekhna", "sunna", "bolna", "karna", "aana", 
    "jana", "puchna", "samajhna", "milna", "dena", "lena", "khareedna", 
    "bechna", "paise", "rupaye", "paisa", "hisab", "bill", "daru", 
    "sharab", "nashe", "chai", "coffee", "doodh", "pani", "botal", 
    "glass", "thanda", "garam", "mitha", "namkeen", "khara", "swaad", 
    "bhook", "pyaas", "nind", "neend", "sone ka", "uthna", "subah", 
    "shaam", "dopahar", "raat", "din", "saal", "mahina", "hafta", 
    "aaj", "kal", "parso", "nindak", "bimar", "doctor", "dawai", 
    "hospital", "dard", "pitta", "sard", "khansi", "bukhar", "jukaam", 
    "tension", "chinta", "fikar", "problem", "samasya", "hal", "upay", 
    "ilaj", "madad", "sahayata", "dost", "dosti", "yaari", "pyaar", 
    "prem", "mohabbat", "nafrat", "gussa", "khushi", "dukh", "dard", 
    "aansoo", "rona", "hasna", "muskurana", "sharmana", "gabrana", 
    "ghabrahat", "dar", "darr", "bhay", "himmat", "dil", "dimag", 
    "soch", "vichar", "khyal", "parivaar", "maa", "papa", "bhai", 
    "behen", "beta", "beti", "dada", "dadi", "nana", "nani", "chacha", 
    "chachi", "mama", "mami", "bua", "phupha", "sala", "saali", "jija", 
    "sali", "bhabhi", "devar", "nanad", "jeth", "jethani", "sasur", 
    "sasuma", "samdhan", "damaad", "bahu", "rishta", "shaadi", "vivah", 
    "shadi", "barat", "dulha", "dulhan", "mandap", "mangalsutra", 
    "sindoor", "mehendi", "sangeet", "reception", "rasam", "vidai", 
    "ghar", "sasural", "peeke", "nanihal", "roka", "sagai", "mangni", 
    "tika", "chunri", "juta", "joota", "churi", "chooda", "kalire", 
    "sehrabandi", "kanyadaan", "pheras", "saptapadi", "kankavaten", 
    "godbharai", "namkaran", "mundan", "annaprashan", "upanayan", 
    "janeu", "thread", "havan", "yagya", "puja", "aarti", "bhajan", 
    "kirtan", "mandir", "masjid", "gurudwara", "church", "devi", 
    "deva", "bhagwan", "ishwar", "allah", "waheguru", "jesus", "mary", 
    "pari", "farista", "rakshas", "pret", "bhoot", "pishach", "chudail", 
    "daayan", "tantrik", "jadu", "totka", "nazar", "najayaz", "haram", 
    "halal", "jannat", "dozakh", "swarg", "narak", "punarjanam", 
    "karma", "dharma", "paap", "punya", "moksh", "mukti", "gyan", 
    "vigyan", "tathya", "sach", "jhuth", "sahi", "galat", "acchai", 
    "burai", "punya", "paap", "daya", "dayaalu", "krpa", "kripa", 
    "ashirwad", "dua", "prarthana", "aashirvaad", "vachan", "vaada", 
    "wada", "kasam", "qasam", "sapath", "shapath", "imandari", 
    "bewafai", "wafadari", "ehsaan", "krtagna", "shukriya", "dhanyavaad", 
    "abhaar", "maafi", "kshama", "sorry", "maaf karo", "maaf kijiye", 
    "shama", "bakhshish", "gunah", "aparadh", "jurm", "saja", "dand", 
    "andekha", "anjaan", "parichit", "parichay", "pehchan", "naam", 
    "naamkaran", "upnaam", "laqab", "khitab", "padavi", "pad", "sthiti", 
    "stithi", "avastha", "dasha", "gati", "chal", "ravani", "disha", 
    "disha", "taraf", "or", "idhar", "udhar", "yahan", "wahan", "kahin", 
    "jahan", "tahan", "jagah", "sth", "jagah","acha", "thik", "sahi", "bilkul", "mast", "dhanyavaad", "shukriya", "kya", "kaise", 
    "kab", "kyun", "kon", "kahan", "kuch", "thoda", "zyada", "kam", "badhiya", "bekar", 
    "dekh", "sun", "bol", "kar", "le", "de", "lo", "bhej", "pakka", "sach", "jhoot", 
    "pyaar", "dost", "yaar", "bhai", "behen", "maa", "papa", "ghar", "kaam", "time", 
    "din", "raat", "subah", "shaam", "kal", "aaj", "parso", "nind", "khana", "peena", 
    "paisa", "mehenga", "sasta", "lalach", "bimari", "doctor", "dawai", "dukaan", 
    "saman", "kapda", "joota", "chhota", "bada", "naya", "purana", "accha", "ganda", 
    "sundar", "besharam", "sharm", "gussa", "khush", "udaas", "darr", "himmat", 
    "majboori", "aish", "maza", "problem", "tension", "chinta", "fayda", "nuksan", 
    "sabun", "pani", "aag", "baarish", "garmi", "sardi", "thand", "garam", "naram", 
    "sakht", "jaldi", "dheere", "andar", "bahar", "upar", "neeche", "aage", "piche", 
    "pass", "door", "idhar", "udhar", "kahin", "abhi", "pehle", "baad", "tak", "se", 
    "par", "mein", "ka", "ki", "ne", "ko", "aur", "ya", "nahi", "haan", "ji", "re", 
    "oh", "arey", "oye", "chalo", "ruk", "aao", "jao", "nikal", "ghumo", "mil", "bata", 
    "samajh", "dekho", "suno", "kaho", "karo", "lo", "do", "rakho", "uthao", "bithao", 
    "sulao", "jagao", "khaao", "piyo", "peelo", "dikhao", "chupao", "dhakao", "kholo", 
    "band", "tod", "phod", "lagao", "hatao", "girao", "uthao", "pakdo", "chhodo", 
    "bhago", "aag", "lago", "banao", "bigado", "becho", "kharido", "sikho", "sikhado", 
    "likho", "padho", "gao", "sunao", "bajao", "nachao", "hasao", "rulao", "darado", 
    "maro", "kato", "kaato", "roko", "choro", "dhoko", "socho", "samjho", "maano", 
    "na", "maano", "karo", "nahi", "karna", "hai", "tha", "ho", "raha", "rahe", "rahi", 
    "rakha", "rakhe", "rakhi", "liya", "lie", "liye", "diya", "die", "diye", "paya", 
    "paye", "pai", "gaya", "gaye", "gayi", "aya", "aye", "ayi", "banaya", "banaye", 
    "banayi", "dekha", "dekhe", "dekhi", "sunna", "sune", "sunni", "bola", "bole", 
    "boli", "kaha", "kahe", "kahi", "kiya", "kiye", "kiyi", "chala", "chale", "chali", 
    "di", "de", "le", "li", "mein", "ne", "se", "par", "ko", "ka", "ki", "aur", "bhi", 
    "phir", "tab", "jab", "toh", "hi", "na", "tha", "the", "thi", "hain", "ho", "hai", 
    "raha", "rahe", "rahi", "rakha", "rakhe", "rakhi", "liya", "lie", "liye", "diya", 
    "die", "diye", "paya", "paye", "pai", "gaya", "gaye", "gayi", "aya", "aye", "ayi", 
    "banaya", "banaye", "banayi", "dekha", "dekhe", "dekhi", "sunna", "sune", "sunni", 
    "bola", "bole", "boli", "kaha", "kahe", "kahi", "kiya", "kiye", "kiyi", "chala", 
    "chale"
]