hinglish_words = [
   "acha", "thik", "hai", "nahi", "hain", "kya", "kar", "raha", "ho", "kaise",
    "bhai", "behen", "papa", "mummy", "dost", "yaar", "sab", "log", "apna", "time",
    "badhiya", "mast", "ghar", "kaam", "phone", "bohot", "zyada", "chota", "bada",
    "dekh", "sun", "bol", "likh", "padh", "khao", "piyo", "aaj", "kal", "parso","arre", "batao", "bhidu", "chill", "dheere", "faltu", "gussa", "hila", "item", "jhakas",
    "khatam", "locha", "majaa", "natak", "olley", "panga", "rukka", "saala", "tension", "ulta",
    "waah", "yaadakash", "zabardast", "bakwaas", "chindi", "dabba", "enthu", "fokat", "golmaal",
    "hungama", "izzat", "jhol", "kaminey", "latka", "maska", "nakhra", "offo", "pareshan", "qismat",
    "rula", "sasti", "tamasha", "ullu", "vella", "wafadar", "xerox", "yeda", "ziddi", "aalsi",
    "bawla", "chhapri", "dhandha", "eww", "fuddu", "gabru", "halkat", "indica", "jhatka", "kaccha",
    "lafda", "maal", "nibba", "okie", "pagalpanti", "randi", "sutta", "timepass", "udao", "vasooli",
    "watt", "xmas", "yoyo", "zombie", "aashiqui", "bamboo", "chumma", "dilbar", "emotional", "flying",
    "gulabi", "haseena", "intzaar", "jannat", "kabootar", "lollipop", "mausam", "nasha", "omlette",
    "pappu", "queen", "roti", "sweetu", "tareef", "ummeed", "vibes", "wifi", "xray", "yummy",
    "zindabad", "aadat", "balle", "chhora", "daru", "expose", "fashion", "goli", "hijra", "itemgirl",
    "jalebi", "khalnayak", "laila", "mawali", "nakhrewali", "outfit", "paisa", "quarter", "rowdy", "sax",
    "tattoo", "undera", "vibe", "wow", "xtra", "yatch", "zorro", "aankh", "bhashan", "chori",
    "dank", "epic", "fokatme", "gandu", "hookah", "inbox", "jugaad", "kismat", "launda", "mauka",
    "nibbi", "outofsyllabus", "pappi", "quick", "rasoi", "saxsux", "tharki", "uncle", "viral", "whaat",
    "xeroxwala", "yoyoji", "zubaan", "aashiq", "bhand", "chutiyapa", "dankmemes", "emo", "fudak", "gandagi",
    "haggu", "insta", "janta", "kalesh", "lafanga", "machau", "nibbu", "oye", "pappubhai", "qubool",
    "randwa", "senti", "thuglife", "unfriend", "vella", "wannabe", "xoxo", "yolo", "zindagi", "aashiqui",
    "bakra", "chutmarika", "dhinchak", "entertain", "firse", "gaand", "hagdo", "irony", "jhakass", "khatarnaak",
    "laundiya", "machayenge", "nibbu", "oyeoye", "pappulog", "quboolhai", "randirona", "sentiho", "thug", "unseen",
    "vella", "wassup", "xeroxwale", "yoyo", "zombie", "aashiqana", "bakchod", "chumtiya", "dhinchakpooja", "emotionalattyachar",
    "din", "raat", "subah", "shaam", "uth", "so", "jaldi", "der", "abhi", "phir",
    "pehle", "baad", "mein", "par", "se", "tak", "bhi", "toh", "hi", "na", "haan",
    "shukriya", "dhanyavaad", "maaf", "karo", "chalo", "aao", "jao", "lo", "do",
    "le", "de", "ruk", "chup", "has", "ro", "daal", "kha", "pi", "dekho", "suno",
    "batao", "samjho", "likho", "padho", "karo", "chahiye", "padega", "aayega",
    "jayega", "aaya", "gaya", "liya", "diya", "khol", "band", "andar", "bahar",
    "upar", "neeche", "aage", "piche", "idhar", "udhar", "kahan", "kahin", "kab",
    "kyun", "kaun", "kisne", "kisko", "kiska", "kitna", "kitne", "aisa", "vaisa",
    "waisa", "jo", "woh", "yeh", "hum", "tum", "aap", "mera", "tera", "hamara",
    "tumhara", "apna", "unka", "inka", "uska", "iska", "sabka", "kiska", "kiski",
    "kisne", "khud", "koi", "kuch", "accha", "bura", "achcha", "bura", "sahi",
    "galat", "naya", "purana", "chai", "paani", "doodh", "roti", "sabzi", "dal",
    "chawal", "shakkar", "namak", "mirch", "haldi", "tel", "aata", "gehu", "chawal",
    "daal", "masala", "khana", "peena", "lena", "dena", "sona", "jagna", "uthna",
    "baithna", "chalna", "bhagna", "hasna", "rona", "gaana", "sunna", "dekna",
    "samjhna", "karna", "aana", "jana", "pina", "khana", "peena", "suna", "dekha",
    "kaha", "liya", "diya", "hua", "hoga", "tha", "thi", "the", "hun", "hoon",
    "hoga", "hogee", "honge", "tha", "thi", "the", "rakho", "rakha", "rakhe",
    "rakhi", "rakha", "rakhe", "rakhi", "rakho", "rakhe", "rakhi", "rakha", "rakhe",
    "rakhi", "rakho", "rakhe", "rakhi", "rakha", "rakhe", "rakhi", "rakho", "rakhe",
    "rakhi", "rakha", "rakhe", "rakhi", "rakho", "rakhe", "rakhi", "rakha", "rakhe",
    "rakhi", "rakho", "rakhe", "rakhi", "rakha", "rakhe", "rakhi", "rakho", "rakhe",
    "rakhi", "rakha", "rakhe", "rakhi", "pyaar", "dil", "dosti", "rishta", "maa",
    "baap", "beta", "beti", "bhai", "behen", "chacha", "chachi", "tau", "tai",
    "dada", "dadi", "nana", "nani", "saas", "sasur", "jija", "sali", "bhabhi",
    "devar", "nanad", "jaan", "jaanu", "baby", "bachcha", "bacche", "ladka",
    "ladki", "launda", "laundi", "buddha", "buddhi", "admi", "aurat", "mard",
    "mahila", "bache", "jawani", "buddhapa", "umr", "saal", "mahina", "hafte",
    "din", "ghanta", "minute", "second", "samay", "waqt", "aajkal", "pehle",
    "abhi", "kal", "parso", "nakshatra", "taara", "chaand", "suraj", "duniya",
    "dharti", "aakash", "paani", "aag", "hawa", "badal", "baarish", "bijli",
    "garam", "thanda", "garmi", "sardi", "barsaat", "jawani", "buddhapa", "umr","acha", "bas", "chalo", "dekho", "dost", "pyaar", "khana", "pani", "ghar", "bhai",
    "behen", "ma", "papa", "bahu", "beta", "sasur", "saas", "nani", "nana", "chacha",
    "chachi", "mausi", "mausa", "bua", "phupha", "dadi", "dada", "ladka", "ladki", "baccha",
    "bache", "badi", "choti", "bara", "chhota", "accha", "bekar", "mast", "sahi", "galat",
    "paise", "rupee", "paisa", "mehenga", "sasta", "daam", "kitna", "kya", "kaun", "kahan",
    "kab", "kyun", "kaise", "par", "magar", "lekin", "aur", "ya", "nahi", "haan",
    "shayad", "bilkul", "sab", "thoda", "zyada", "kam", "badhiya", "bekaar", "daru", "sharab",
    "nashta", "subah", "shaam", "raat", "din", "saal", "mahina", "hafta", "aaj", "kal",
    "parso", "nind", "neend", "sone", "uthna", "khana", "peena", "piyo", "khao", "daal",
    "roti", "chawal", "sabzi", "doodh", "chai", "coffee", "chini", "namak", "mirch", "masala",
    "haldi", "jeera", "dhaniya", "adrak", "lasun", "pyaaz", "tamatar", "baingan", "aloo", "gobi",
    "gajar", "matar", "palak", "karela", "bhindi", "kela", "seb", "aam", "santra", "angoor",
    "anar", "nariyal", "kaju", "badam", "kishmish", "chawal", "dal", "chana", "rajma", "moong",
    "urad", "chole", "besan", "atta", "maida", "sooji", "poha", "upma", "idli", "dosa",
    "sambar", "vada", "puri", "paratha", "litti", "chokha", "samosa", "kachori", "jalebi", "gulab",
    "jamun", "rasgulla", "barfi", "ladoo", "halwa", "kheer", "rabri", "malai", "dahi", "chaas",
    "lassi", "shikanji", "nimbu", "paani", "thanda", "garam", "chai", "doodh", "chini", "elaichi",
    "kapda", "suit", "saree", "lehnga", "salwar", "kameez", "kurta", "pajama", "dhoti", "topi",
    "joota", "chappal", "mojri", "bangle", "churi", "jhumka", "nath", "bindi", "mehndi", "kajal",
    "sindoor", "bichiya", "kamarband", "ghar", "makaan", "kothi", "bangla", "barsati", "dewar", "khidki",
    "darwaza", "chhat", "diwar", "farsh", "bistar", "takya", "chadar", "razai", "almari", "pankha",
    "cooler", "AC", "TV", "fridge", "washing", "machine", "mixer", "grinder", "chimta", "belan",
    "chamach", "katori", "thali", "glass", "jug", "bucket", "mug", "soap", "shampoo", "tel",
    "kapoor", "agarbatti", "dhoop", "pooja", "mandir", "bhagwan", "devi", "deva", "puja", "aarti",
    "prasad", "naivedya", "vrat", "upvas", "tyohar", "diwali", "holi", "rakhi", "eid", "christmas",
    "ganesh", "saraswati", "lakshmi", "durga", "kali", "shiv", "vishnu", "ram", "krishna", "hanuman",
    "sai", "allah", "khuda", "jesus", "guru", "nanak", "mahadev", "parvati", "radha", "sita",
    "savitri", "ganga", "yamuna", "saraswati", "kaveri", "godavari", "narmada", "tulsi", "peepal", "neem",
    "gulab", "champa", "chameli", "mogara", "juhi", "bela", "davana", "ketaki", "kadam", "ashok",
    "bahar", "patjhad", "sardi", "garmi", "barsaat", "jhadi", "aandhi", "toofan", "bijli", "badal",
    "dhoop", "chhaya", "nadi", "sagar", "samundar", "pahar", "jungle", "ped", "paudha", "phool",
    "patte", "tinka", "ghas", "khet", "kisan", "hal", "bullock", "tractor", "bij", "khad",
    "fasal", "anna", "daana", "bhusa", "charra", "gobar", "kooda", "safai", "jhadu", "pochha",
    "kapda", "safedi", "dhoop", "sabun", "tel", "kapoor", "agarbatti", "dhoop", "diya", "mombatti",
    "lalten", "bijli", "meter", "bill", "paani", "nal", "tanki", "pump", "motor", "kua",
    "chhaja", "verandah", "angan", "chabutra", "gali", "sadak", "rasta", "marg", "chauraha", "crossing",
    "signal", "traffic", "police", "thana", "chowki", "daroga", "hakim", "netaji", "neta", "MLA",
    "MP", "pradhan", "sarpanch", "pati", "patni", "sasural", "maika", "rishta", "roka", "mangni",
    "shaadi", "baraat", "dulha", "dulhan", "jaimala", "pheras", "kanyadaan", "vidai", "reception", "mandap",
    "mehendi", "sangeet", "haldi", "chooda", "kalire", "sehra", "ghoonghat", "chunri", "laaja", "havan",
    "pandit", "purohit", "kundali", "gotra", "muhurat", "shagun", "dahej", "joota", "chhupai", "rasam",
    "varat", "kanku", "aashirwad", "pranam", "charan", "sparsh", "guru", "shishya", "vidya", "gyan",
    "kala", "kaushal", "hunar", "udyog", "vyapar", "dhandha", "naukri", "chakri", "kamai", "paisa",
    "loot", "daaku", "chor", "chori", "safedi", "imaandar", "bewakoof", "chatur", "chalak", "bhola",
    "seedha", "tedha", "ulta", "sidha", "ooncha", "neecha", "lamba", "chhota", "mota", "patla",
    "gadha", "motu", "chhotu", "bada", "chhota", "accha", "bura", "sundar", "khoobsurat", "badsoorat",
    "badtameez", "shareef", "sanskaari", "awara", "mast", "majnu", "deewana", "pagal", "paagal", "sanam",
    "jaan", "dil", "dost", "yaar", "mitr", "saathi", "sathi", "sang", "prem", "sneh",
    "mohabbat", "ishq", "pyaar", "chaahat", "dil", "man", "tan", "jism", "rooh", "atma",
    "pran", "jivan", "mrityu", "janam", "maran", "karma", "dharma", "moksh", "swarg", "narak",
    "paap", "punya", "puja", "archana", "bhajan", "kirtan", "satsang", "pravachan", "katha", "updesh",
    "guru", "chela", "shraddha", "vishwas", "astha", "bhakti", "shakti", "daya", "kshama", "dana",
    "tapa", "tyag", "satya", "ahinsa", "brahmacharya", "aparigraha", "shauch", "santosh", "swadhyay", "ishwar",
    "pranidhan", "yoga", "dhyan", "samadhi", "sadhana", "tapasya", "siddhi", "riddhi", "maya", "moh",
    "ahankar", "lobh", "krodh", "matsar", "irsha", "dwesh", "prem", "daya", "karuna", "maitri",
    "mudita", "upeksha", "shanti", "sukh", "dukh", "santosh", "trishna", "vairagya", "vivek", "vichar",
    "gyan", "vigyan", "tattva", "darshan", "mimansa", "nyaya", "vaisheshik", "sankhya", "yoga", "vedanta",
    "smriti", "puran", "itihas", "mahakavya", "kavya", "natak", "nibandh", "lekhan", "patra", "katha",
    "kahani", "upanyas", "nibandh", "pady", "gadya", "chhanda", "alankar", "ras", "bhava", "dhwani",
    "varn", "shabd", "arth", "vyakarana", "sandhi", "samasa", "karak", "kriya", "kaal", "purush",
    "vachan", "ling", "vibhakti", "pratyay", "upsarg", "avyay", "sangya", "sarvnam", "visheshan", "kriya",
    "kriya", "sambandh", "yojak", "chinh", "viram", "bindu", "ardh", "purn", "prashn", "udgar",
    "aashcharya", "sammati", "naman", "upmaan", "dhyan", "sankalp", "pratigya", "prarambh", "samapti", "nirnay",
    "sankat", "samadhan", "yojana", "karyakram", "prakriya", "paddhati", "tantra", "yantra", "mantra", "yantra",
    "kriya", "puja", "havan", "yagya", "tarpan", "shradh", "pind", "daan", "tirth", "yatra",
    "teerth", "darshan", "mahatmya", "stotra", "ashtak", "sahasranam", "kavach", "arti", "mangal", "bhog",
    "prasad", "naivedya", "phal", "pushp", "patra", "dhoop", "deep", "akshata", "chandan", "kumkum",
    "haldi", "moli", "dhaga", "kalava", "nariyal", "phool", "mala", "haar", "sehra", "toran",
    "rangoli", "alpana", "mandala", "chauk", "purna", "swastik", "om", "shanti", "ram", "shyam",
    "hare", "krishna", "govind", "gopal", "madhav", "mohan", "shiv", "shankar", "bholenath", "mahadev",
    "nataraj", "ardhnarishwar", "parvati", "uma", "gauri", "durga", "kali", "sati", "savitri", "sita",
    "radha", "meera", "annapurna", "lakshmi", "saraswati", "ganga", "yamuna", "saryu", "godavari", "narmada",
    "kaveri", "tungabhadra", "krishna", "brahmaputra", "sindhu", "saraswati", "sabarmati", "chambal", "betwa", "ken",
    "son", "damodar", "mahanadi", "tapi", "mah", "kosi", "gandak", "ghaghra", "yamuna", "sarayu",
    "gomti", "ghagra", "sharda", "kali", "teesta", "ravi", "beas", "sutlej", "chenab", "jhelum",
    "indus", "ganga", "narmada", "godavari", "kaveri", "krishna", "tungabhadra", "mahanadi", "brahmaputra", "saraswati",
    "sindhu", "sabarmati", "chambal", "betwa", "ken", "son", "damodar", "tapi", "mah", "kosi",
    "gandak", "ghaghra", "sarayu", "gomti", "ghagra", "sharda", "kali", "teesta", "ravi", "beas",
    "sutlej", "chenab", "jhelum", "indus", "ganga", "narmada", "godavari", "kaveri", "krishna", "tungabhadra",
    "mahanadi", "brahmaputra", "saraswati", "sindhu", "sabarmati", "chambal", "betwa", "ken", "son", "damodar",
    "tapi", "mah", "kosi", "gandak", "ghaghra", "sarayu", "gomti", "ghagra", "sharda", "kali",
    "teesta", "ravi", "beas", "sutlej", "chenab", "jhelum", "indus", "ganga", "narmada", "godavari",
    "kaveri", "krishna", "tungabhadra", "mahanadi", "brahmaputra", "saraswati", "sindhu", "sabarmati", "chambal", "betwa",
    "ken", "son", "damodar", "tapi", "mah", "kosi", "gandak", "ghaghra", "sarayu", "gomti",
    "ghagra", "sharda", "kali", "teesta", "ravi", "beas", "sutlej", "chenab", "jhelum", "indus",
    "ganga", "narmada", "godavari", "kaveri", "krishna", "tungabhadra", "mahanadi", "brahmaputra", "saraswati", "sindhu",
    "sabarmati", "chambal", "betwa", "ken", "son", "damodar", "tapi", "mah", "kosi", "gandak",
    "ghaghra", "sarayu", "gomti", "ghagra", "sharda", "kali", "teesta", "ravi", "beas", "sutlej",
    "chenab", "jhelum", "indus", "ganga", "narmada", "godavari", "kaveri", "krishna", "tungabhadra", "mahanadi",
    "brahmaputra", "saraswati", "sindhu", "sabarmati", "chambal", "betwa", "ken", "son", "damodar", "tapi",
    "mah", "kosi", "gandak", "ghaghra", "sarayu", "gomti", "ghagra", "sharda", "kali", "teesta",
    "ravi", "beas", "sutlej", "chenab", "jhelum", "indus", "ganga", "narmada", "godavari", "kaveri",
    "krishna", "tungabhadra", "mahanadi", "brahmaputra", "saraswati", "sindhu", "sabarmati", "chambal", "betwa", "ken",
    "son", "damodar", "tapi", "mah", "kosi", "gandak", "ghaghra", "sarayu", "gomti", "ghagra",
    "sharda", "kali", "teesta", "ravi", "beas", "sutlej", "chenab", "jhelum", "indus", "ganga",
    "narmada", "godavari", "kaveri", "krishna", "tungabhadra", "mahanadi", "brahmaputra", "saraswati", "sindhu", "sabarmati"]