minglish_words = [
    "aai", "baba", "mulga", "mulgi", "ghar", "paus", "doka", "motha", 
    "chota", "navra", "navri", "dudh", "tup", "bhat", "bhaji", "usal", 
    "poha", "upwas", "varan", "bhaat", "khichdi", "pithla", "zunka", 
    "bhakri", "poli", "thecha", "lasun", "mirchi", "kanda", "batata", 
    "vangi", "kobi", "fulkobi", "dudhbhat", "masala", "halad", "mirchi", 
    "jeera", "dhania", "hing", "ajinomoto", "limbu", "fodnichi", "shev", 
    "bhaji", "chinch", "gul", "tup", "sakhar", "kat", "goda", "mittha", 
    "tikat", "khar", "ambat", "khatta", "phodita", "phodala", "kadhayla", 
    "vadhavayla", "bolayla", "aikayla", "baghayla", "dakhavayla", "gheun", 
    "deun", "ghyal", "utha", "nigha", "basla", "jhopla", "uthala", "khel", 
    "khelayla", "hasayla", "radla", "gappa", "bolu", "bolnaar", "aika", 
    "sangayla", "vatta", "vattayla", "samajla", "kalala", "mahit", "navta", 
    "navhay", "aata", "udya", "kaal", "parva", "divas", "ratri", "sakali", 
    "dupari", "sanje", "ratri", "pahate", "madhye", "madhye", "nantar", 
    "aata", "mag", "khara", "khari", "khare", "sagle", "konti", "koni", 
    "kase", "kashi", "kay", "kiti", "evdha", "tevdha", "itka", "titka", 
    "asa", "tasa", "ekda", "pardha", "kahi", "kuthla", "kuthe", "ikde", 
    "tikde", "jara", "thoda", "masta", "chhan", "bara", "changa", "vait", 
    "barobar", "chuku", "bara", "khup", "fara", "nako", "naka", "nahi", 
    "ho", "na", "pan", "ani", "kinva", "mhanun", "tar", "parantu", "karan", 
    "mule", "ashi", "tashi", "majha", "tujha", "tyacha", "amcha", "tumcha", 
    "tyancha", "konacha", "mazyakade", "tujhyakade", "tyachyakade", 
    "amchyakade", "tumchyakade", "tyanchakade", "konachakade", "mazyashi", 
    "tujhyashi", "tyachyashi", "amchyashi", "tumchyashi", "tyanchashi", 
    "konachashi", "mazyavar", "tujhyavar", "tyachyavar", "amchyavar", 
    "tumchyavar", "tyanchavar", "konachavar", "aat", "patt", "dol", "ang", 
    "hat", "pay", "dok", "nakh", "kes", "tond", "dant", "nag", "mama", 
    "mami", "kaka", "kaku", "dada", "dadi", "nana", "nani", "bhau", "vahini", 
    "maushi", "mama", "atya", "kaku", "baba", "aai", "dada", "vahini", 
    "mulga", "mulgi", "soyare", "mitra", "dost", "aapte", "olakh", "navin", 
    "janiv", "manus", "jan", "lok", "stri", "purush", "bala", "mulya", 
    "mhatara", "vrudh", "tarun", "yuvak", "yuvati", "kumari", "kunbi", 
    "maratha", "brahman", "kshatriya", "vaishya", "shudra", "mahant", 
    "sadhu", "fakir", "mulla", "pandit", "maulvi", "padri", "father", 
    "sister", "dada", "didi", "anna", "akka", "bhai", "tai", "kaku", 
    "kaki", "dada", "kaka", "bhauji", "didi", "vahini", "atya", "kaku", 
    "mavshi", "mama", "bhau", "aaji", "nana", "nani", "dada", "dadi", 
    "soyare", "natu", "maitrin", "mitra", "dost", "aapta", "olakh", 
    "navin", "janiv", "manoos", "jan", "lok", "stri", "purush", "bala", 
    "mulya", "mhatare", "vrudha", "tarun", "yuvak", "yuvati", "kumari", 
    "kunbi", "maratha", "brahman", "kshatriya", "vaishya", "shudra", 
    "mahant", "sadhu", "fakir", "mulla", "pandit", "maulvi", "padri", 
    "father", "sister", "anna", "akka", "bhai", "tai", "kaku", "kaki", 
    "dada", "kaka", "bhauji", "didi", "vahini", "atya", "kaku", "mavshi", 
    "mama", "bhau", "aaji", "nana", "nani", "dada", "dadi", "soyare", 
    "natu", "maitrin", "mitra", "dost", "aapta", "olakh", "navin", "janiv", 
    "manoos", "jan", "lok", "stri", "purush", "bala", "mulya", "mhatare", 
    "vrudha", "tarun", "yuvak", "yuvati", "kumari", "kunbi", "maratha", 
    "brahman", "kshatriya", "vaishya", "shudra", "mahant", "sadhu", 
    "fakir", "mulla", "pandit", "maulvi", "padri", "father", "sister", 
    "anna", "akka", "bhai", "tai", "kaku", "kaki", "dada", "kaka", 
    "bhauji", "didi", "vahini", "atya", "kaku", "mavshi", "mama", "bhau", 
    "aaji", "nana", "nani", "dada", "dadi", "soyare", "natu", "maitrin", 
    "mitra", "dost", "aapta", "olakh", "navin", "janiv", "manoos", "jan", 
    "lok", "stri", "purush", "bala", "mulya", "mhatare", "vrudha", "tarun", 
    "yuvak", "yuvati", "kumari", "kunbi", "maratha", "brahman", "kshatriya", 
    "vaishya", "shudra", "mahant", "sadhu", "fakir", "mulla", "pandit", 
    "maulvi", "padri", "father", "sister", "anna", "akka", "bhai", "tai", 
    "kaku", "kaki", "dada", "kaka", "bhauji", "didi", "vahini", "atya", 
    "kaku", "mavshi", "mama", "bhau", "aaji", "nana", "nani", "dada", 
    "dadi", "soyare", "natu", "maitrin", "mitra", "dost", "aapta", 
    "olakh", "navin", "janiv", "manoos", "jan", "lok", "stri", "purush", 
    "bala", "mulya", "mhatare", "vrudha", "tarun", "yuvak", "yuvati", 
    "kumari", "kunbi", "maratha", "brahman", "kshatriya", "vaishya", 
    "shudra", "mahant", "sadhu", "fakir", "mulla", "pandit", "maulvi", 
    "padri", "father", "sister", "anna", "akka", "bhai", "tai", "kaku", 
    "kaki", "dada", "kaka", "bhauji", "didi", "vahini", "atya", "kaku", 
    "mavshi", "mama", "bhau", "aaji", "nana", "nani", "dada", "dadi", 
    "soyare", "natu", "maitrin", "mitra", "dost", "aapta", "olakh", 
    "navin", "janiv", "manoos", "jan", "lok", "stri", "purush", "bala", 
    "mulya", "mhatare", "vrudha", "tarun", "yuvak", "yuvati", "kumari", 
    "kunbi", "maratha", "brahman", "kshatriya", "vaishya", "shudra",
    "aamboli", "aata", "aathvan", "aboli", "adki", "agadi", "akkal", "akur", "aliv", 
    "ambada", "ambe", "amti", "ananas", "angat", "angithi", "anjir", "ankhi", "aple", 
    "arvi", "asel", "avala", "badam", "badha", "bagh", "bahir", "bakri", "bal", "balant", 
    "balgandharva", "balutedar", "bandi", "barik", "basan", "bavta", "bedi", "bhadak", 
    "bhaji", "bhakar", "bhandara", "bharal", "bharli", "bhatukli", "bhav", "bhint", 
    "bhogi", "bhurta", "bichu", "bilamba", "birde", "bohadi", "bor", "bot", "botal", 
    "bov", "brahman", "bujji", "burfi", "chaha", "chakli", "chamach", "chamatkar", 
    "chambhar", "chan", "chandu", "chang", "charoli", "chav", "chavan", "chawl", 
    "chikhal", "chikna", "chilim", "chilya", "chimb", "china", "chindi", "chivda", 
    "chokha", "chombu", "chor", "chori", "chota", "chuk", "chuli", "chun", "churan", 
    "dabba", "dahi", "dakhal", "dakhla", "dal", "dali", "damaal", "dand", "dandu", 
    "danka", "dapoli", "dar", "darinda", "darpan", "darwaja", "daryacha", "dastak", 
    "dav", "davkar", "deh", "dehla", "dehva", "dekh", "denda", "deol", "dev", "devak", 
    "devhara", "devrukh", "dhab", "dhadak", "dhadkan", "dhadphod", "dhaga", "dhak", 
    "dhal", "dhamal", "dhand", "dhangar", "dhanu", "dhar", "dharak", "dharavi", 
    "dhol", "dholak", "dhong", "dhotar", "dhu", "dhula", "dhurpad", "dhyas", "diwas", 
    "diwli", "dodka", "dodma", "dokya", "dol", "dola", "dolkar", "domb", "dombivli", 
    "donda", "dongar", "doodh", "dopahar", "dorma", "dosa", "dost", "dudh", "duk", 
    "dukan", "dumal", "dungar", "dungri", "dusri", "dvandva", "ekad", "ekda", "ekka", 
    "elaneer", "fajiti", "fakta", "fanas", "faral", "fatak", "fatfati", "fugadi", 
    "ful", "fule", "fulpakhru", "gabha", "gad", "gadbad", "gadhav", "gadi", "gadicha", 
    "gajra", "galicha", "gamcha", "gammat", "gan", "gana", "ganesh", "gani", "garaj", 
    "garam", "garbad", "gard", "garguti", "garib", "garja", "gatha", "gatka", "gav", 
    "gavat", "gavathi", "gavran", "gavthi", "gay", "ghad", "ghadi", "ghagar", "ghai", 
    "ghal", "gham", "ghanta", "ghar", "gharguti", "ghat", "ghatan", "ghati", "ghatka", 
    "ghav", "ghoda", "ghongadi", "ghot", "ghugari", "ghumat", "gila", "girni", 
    "goad", "gobar", "god", "godadi", "godavari", "godi", "gol", "gola", "gole", 
    "goli", "gond", "gondhal", "goph", "gor", "gora", "gotya", "goval", "govinda", 
    "gubgub", "gud", "guddi", "gul", "gulab", "gulal", "gulati", "gulcha", "guli", 
    "gulmohar", "guluchi", "gumat", "gun", "gunha", "guntha", "gupchup", "gur", 
    "gurav", "guruji", "gutka", "guzar", "haad", "haak", "haath", "habba", "hadak", 
    "hadapsar", "hadta", "hadval", "hagna", "haka", "hakim", "halad", "haldi", 
    "halga", "haliv", "halva", "hamal", "hamber", "han", "handi", "hang", "hani", 
    "hapus", "har", "harav", "harda", "hariali", "haripath", "harni", "hat", "hatadi", 
    "hatak", "hatta", "havaldar", "haveli", "havi", "havya", "hed", "heera", "hel", 
    "hela", "helava", "him", "hing", "hinga", "hingoli", "hirva", "his", "hisab", 
    "hivar", "hol", "holi", "holyachi", "honi", "hop", "hos", "hota", "hotel", "hov", 
    "hudak", "hujur", "hula", "hum", "hun", "hunda", "hundi", "hut", "hutatma", 
    "ib", "ichha", "id", "idda", "il", "ilakha", "ilane", "indhan", "indori", "ingla", 
    "inam", "ip", "isak", "isap", "ishara", "it", "itki", "ivcha", "ivha", "jaad", 
    "jaadu", "jaag", "jaal", "jaam", "jaan", "jaanavar", "jaat", "jabh", "jada", 
    "jadi", "jaga", "jagha", "jagnya", "jaha", "jai", "jail", "jaka", "jakhmi", 
    "jal", "jalgaon", "jalim", "jalja", "jalna", "jalwa", "jam", "jamai", "jamb", 
    "jambhul", "jambya", "jami", "jamla", "jamun", "jana", "janav", "janiva", 
    "janma", "jara", "jarab", "jari", "jaripatka", "jata", "jatha", "jatka", "jatra", 
    "jau", "jav", "javai", "javak", "javal", "javi", "javla", "jhaad", "jhad", "jhaka", 
    "jhakka", "jhal", "jham", "jhanda", "jhanjhar", "jhar", "jharna", "jhat", "jhatka", 
    "jhav", "jhil", "jhoka", "jhol", "jhopa", "jhopdi", "jhota", "jhum", "jhun", 
    "jhunjh", "jhup", "jhus", "jhya", "jhyal", "jil", "jila", "jilha", "jimma", 
    "jinti", "jira", "jiv", "jiva", "jivha", "jivrakh", "jivti", "jnyan", "jod", 
    "jog", "jogava", "jogeshwari", "jogi", "jogwa", "joka", "jol", "jola", "jondha", 
    "jop", "jor", "jota", "jotish", "jowar", "jua", "jucha", "judi", "jula", "julab", 
    "juna", "juni", "junta", "jura", "juri", "juta", "jutika", "juvva", "jwal", 
    "jwar", "jyot", "jyoti", "jyotish", "kaaj", "kaaka", "kaaki", "kaal", "kaala", 
    "kaanda", "kaanth", "kaar", "kaas", "kaata", "kaath", "kaav", "kabadi", "kabara", 
    "kabja", "kabootar", "kabutar", "kacha", "kadak", "kadamba", "kadane", "kadboli", 
    "kaddi", "kade", "kadi", "kadhi", "kadipatta", "kadit", "kadkada", "kadla", 
    "kadod", "kadu", "kadva", "kadvi", "kafan", "kagad", "kagal", "kagaz", "kaha", 
    "kahani", "kahi", "kahipan", "kahir", "kailas", "kajal", "kajar", "kaju", "kaka", 
    "kakad", "kakana", "kakdi", "kaksha", "kala", "kalal", "kalam", "kalan", 
    "kalas", "kalat", "kalav", "kalgi", "kali", "kalij", "kalingad", "kalka", 
    "kalla", "kalok", "kals", "kalsada", "kalti", "kalu", "kalya", "kam", "kamal", 
    "kamar", "kamba", "kambal", "kamble", "kamee", "kami", "kamit", "kamla", "kamod", 
    "kan", "kana", "kanadi", "kanak", "kanala", "kancha", "kand", "kanda", "kande", 
    "kandil", "kang", "kanga", "kangal", "kangi", "kanha", "kani", "kanishta", 
    "kanjak", "kank", "kanka", "kankal", "kankavli", "kankotri", "kanku", "kantha", 
    "kanti", "kanu", "kapal", "kapda", "kapil", "kapu", "kapus", "kar", "kara", 
    "karad", "karadi", "karaj", "karak", "karal", "karamb", "karan", "karanda", 
    "karandi", "karane", "karani", "karat", "karbhari", "karchul", "kardu", "karela", 
    "karga", "karja", "kark", "karma", "karna", "karodi", "kartik", "karu", "karuna", 
    "karve", "kas", "kasa", "kasab", "kasar", "kasav", "kase", "kashi", "kashta", 
    "kasti", "kasur", "kat", "kata", "katak", "katal", "katar", "katha", "kathin", 
    "kati", "katil", "katkar", "katla", "katol", "katra", "katta", "kattu", "kava", 
    "kavad", "kavach", "kaval", "kavala", "kavath", "kavda", "kavdi", "kavi", "kavla", 
    "kavtha", "kay", "kayak", "kayde", "kayra", "kayu", "kela", "kelav", "keli", 
    "kelwa", "kem", "kemp", "ken", "kend", "kendra", "kep", "ker", "kes", "kesar", 
    "keshari", "keshri", "kesu", "ketak", "ketki", "kewda", "khadak", "khadki", 
    "khado", "khai", "khajina", "khak", "khal", "khalat", "khalcha", "khalchi", 
    "khalge", "khalit", "khall", "khalna", "khalun", "khaman", "khamang", "khamat", 
    "khamba", "khambe", "khamgaon", "khamir", "khan", "khana", "khand", "khandar", 
    "khandesh", "khandoba", "khandvi", "khane", "khani", "khankhoje", "khapra", 
    "khar", "kharadi", "kharak", "kharat", "kharch", "kharda", "khare", "khari", 
    "kharicha", "kharid", "khariv", "khark", "kharsan", "kharvas", "khat", "khatak", 
    "khatal", "khatar", "khatav", "khatka", "khatri", "khatu", "khav", "khava", 
    "khawas", "khazan", "khichadi", "khidki", "khil", "khila", "khilari", "khilat", 
    "khile", "khilone", "khinvasara", "khira", "khiste", "khob", "khobra", "khoj", 
    "khol", "khom", "khomcha", "khona", "khone", "khong", "khope", "khopoli", 
    "khor", "khota", "khotach", "khotya", "khoya", "khud", "khuj", "khula", "khulad", 
    "khumbar", "khunti", "khurak", "khurchi", "khurd", "khurma", "khursi", "khushi", 
    "khusk", "khut", "khutba", "khutya", "khwab", "khyal", "kinara", "king", "kini", 
    "kirmir", "kirpan", "kirtan", "kisan", "kismat", "kiti", "kivha", "kizad", "koba", 
    "kodi", "kohli", "koka", "kokan", "kokani", "kokam", "koli", "kolhapuri", "koli", 
    "kombda", "komdi", "kond", "kondwa", "koni", "kop", "kopra", "kora", "koregaon", 
    "kosh", "koshimbir", "kot", "kotambi", "kotwal", "kovi", "koyta", "koyna", "kraal", 
    "kram", "kranti", "krida", "krishi", "krushak", "kubdi", "kuda", "kudav", "kudi", 
    "kudka", "kudmud", "kudu", "kudva", "kujli", "kukdi", "kukna", "kula", "kuladaivat", 
    "kular", "kulav", "kuli", "kulit", "kullu", "kumbh", "kumbhar", "kumbhi", "kumkum", 
    "kunda", "kundal", "kuni", "kunku", "kup", "kura", "kuran", "kurchi", "kurdai", 
    "kuri", "kurha", "kurla", "kurmura", "kuro", "kusal", "kush", "kusti", "kuthe", 
    "kutra", "kutrya", "kuvar", "kuwar", "kuzu", "kyari", "laad", "laav", "labad", 
    "labha", "labharthi", "labharthi", "lachak", "lachka", "lad", "ladachi", "ladki", 
    "ladu", "lagna", "lagu", "lahar", "lahi"
]